### ISSUE TITLE
When i load pivot in landscape mode table is not taking full width.

### ISSUE THREAD

**Issue by nimeshbhalani** [flexmonster/react-flexmonster#3]
![Simulator Screen Shot - iPhone X - 2020-05-13 at 11 23 49](https://user-images.githubusercontent.com/24494874/81776328-43ed6900-950c-11ea-8daf-b0bd134d2de9.png)

**Comment by mhalaida** [comment]
Hi @nimeshbhalani,

Thank you for posting your question.

We've tested this on our side and didn't manage to reproduce the described behavior using our sample project on GitHub: https://github.com/flexmonster/pivot-react/tree/master/ES6 

We would suggest trying to resize the pivot table container to make sure there is enough space for Flexmonster to be drawn.

Please let us know if this helps.

Best regards,
Mykhailo

**Comment by mhalaida** [comment]
Hi @nimeshbhalani 
 
We are writing to let you know that a similar issue has been reported with [React Native](https://github.com/flexmonster/react-native-flexmonster) – if you've been using RN as well, we are glad to announce it has been fixed with the latest Flexmonster release – you are welcome to update the component.

Also, in case this helps, we have a sample React Native project on GitHub which you can refer to: https://github.com/flexmonster/pivot-react-native

Please let us know if this helps.

Regards,
Mykhailo
